#!/bin/sh

PREFIX="$(tr -dc a-z </dev/urandom | head -c 32)"

FILENAME="$PREFIX$1"

# If on linux, stores file under /dev/shm to 
# avoid using the Hard Drive/SSD
if "$(uname)" -eq "Linux"; then
	TEMP_FILE="/dev/shm/$FILENAME"
else
	TEMP_FILE="/tmp/$FILENAME"
fi

case "$FILENAME" in
	*.h*)
		GUARD_NAME="$(echo $1 | tr "[:lower:]." "[:upper:]_")"
		PREFIXED_GUARD_NAME="$(echo "$FILENAME" | tr "[:lower:]." "[:upper:]_")"
		cat | sed "s/$GUARD_NAME/$PREFIXED_GUARD_NAME/g" > "$TEMP_FILE"
		;;
	*)
		cat > "$TEMP_FILE"
		;;
esac

norminette "$TEMP_FILE"
rm "$TEMP_FILE"
